title: Patrick's Blog
remote_theme: lorepirri/cayman-blog
markdown: kramdown
highlighter: rouge
color_scheme: light
url: "https://blog.jolliffe.hk"
collections:
  _drafts_public:
    output: true